version: 1.16.{build}.0
image: Visual Studio 2019
build_script:
- ps: .\build.ps1
artifacts:
- path: 'bin**\*.lib'
- path: 'bin**\*.dll'
- path: 'bin**\*.pdb'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true