version: 1.21.{build}.0
image: Visual Studio 2019
skip_commits:
  files:
    - '**/*.md'
    - '**/*.aip'
cache:
- C:\projects\DMF
- C:\projects\ViGEmBus\vpatch.exe
platform:
- x86
- x64
- ARM64
configuration:
- Release
environment:
  DmfRootPath: C:\projects\DMF
install:
- cmd: git submodule -q update --init
- cmd: git clone -q https://github.com/microsoft/DMF.git C:\projects\DMF 2> nul || set ERRORLEVEL=0
- cmd: |
    cd "C:\projects\DMF"
    git pull > NUL
    git apply --reject "%APPVEYOR_BUILD_FOLDER%\patches\dmf.diff 2> NUL
    cd %appveyor_build_folder%
before_build:
- ps: Invoke-WebRequest "https://github.com/nefarius/vpatch/releases/latest/download/vpatch.exe" -OutFile vpatch.exe
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\sys\ViGEmBus.vcxproj" --vcxproj.inf-time-stamp
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\sys\ViGEmBus.rc" --resource.file-version --resource.product-version
build_script:
- cmd: .\build.cmd
after_build:
- cmd: makecab.exe /f ViGEmBus_%PLATFORM%.ddf
artifacts:
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.inf'
- path: 'bin**\$(APPVEYOR_PROJECT_NAME)\*.sys'
- path: 'bin**\*.pdb'
- path: 'disk1\*.cab'
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true