blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Community support
    url: https://vigem.org/Community-Support/
    about: Use these resources for support.
  - name: ğŸ“– Documentation
    url: https://vigem.org/projects/
    about: Extended documentation about the projects.
  - name: â“ Other issue?
    url: https://forums.vigem.org/
    about: Search on the community forums.
