blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Community support
    url: https://docs.nefarius.at/Community-Support/
    about: Use these resources for support.
  - name: ğŸ“– Documentation
    url: https://docs.nefarius.at/projects/
    about: Extended documentation about the projects.
  - name: â“ Other issue?
    url: https://discord.nefarius.at/
    about: See you on Discord.
